#!/usr/bin/env python3

import roslib
import rospy

from dashboard_interface_node.main import DashboardInterfaceNode

NODE_NAME = 'dashboard_interface_node'
roslib.load_manifest(NODE_NAME)

if __name__ == '__main__':
    rospy.init_node(NODE_NAME)
    try:
        node = DashboardInterfaceNode()
    except rospy.ROSInterruptException:
        pass
